sudo: false

language: node_js
node_js:
  - "4.0"
  - "5.0"
  - "6.0"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

install:
  - npm prune
  - npm install

notifications:
  email: false
